categories:
    karaoke:
        - "ğŸµ"
        - "karaoke"
        - "sing"
        - "æ­Œ"
        - "ğŸ¤"
    asmr:
        - "asmr"
        - "ku100"
    unarchived:
        - "archive"
        - "ã‚¢ãƒ¼ã‚«ã‚¤ãƒ–ãªã—"

locations:
    tmp: /tmp/hololive/
    final: /downloads/ # A karaoke stream would go to /downloads/karaoke/stream title.mkv
