categories:
    karaoke:
        - "ğŸµ"
        - "karaoke"
        - "sing"
    asmr:
        - "asmr"
    game:
        - "undertale"

locations:
    tmp: /mnt/array/tmp/
    final: /mnt/array/hololive/